[tool.ruff]
line-length = 88
exclude = ["__pycache__", ".venv"]

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "S", "TID", "FAST"]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
